name: Observability Stack 

on:
  workflow_call:
   secrets:
     AWS_REGION:
      required: true
     AWS_ACCESS_KEY:
       required: true
     AWS_SECRET_KEY:
       required: true

jobs:
  observability_stack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY  }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install Vkpr
        shell: bash
        run: |
          curl -fsSL https://get.vkpr.net/ | CONTROL_SKIP="true" bash
          rit update repo --name="vkpr-cli" --version=1.3.5


      ### Configure VKPR Credentials
      - name: config vkpr credentials
        shell: bash
        run: |
            alias vkpr="rit vkpr"
            rit set credential --provider="aws" \
                --fields="accesskeyid,region,secretaccesskey" \
                --values="${{'${{'}} secrets.AWS_ACCESS_KEY ${{'}}'}},${{'${{'}} secrets.AWS_REGION ${{'}}'}},${{'${{'}} secrets.AWS_SECRET_KEY ${{'}}'}}" 

      - name: Vkpr apply
        run: |
          
          alias vkpr="rit vkpr"
          aws eks update-kubeconfig --name ${{'${{'}} secrets.CLUSTER_NAME${{'}}'}} --region ${{'${{'}} secrets.AWS_REGION${{'}}'}}
          rit vkpr apply --path_to_file="$(pwd)/vkpr.yaml"

      - name: Upload kubeconfig file as artefact
        uses: actions/upload-artifact@v2
        with:
          name: kubeconfig
          path: ~/.kube/config
